<form id="my-form"
    data-mage-init='{"validation":{}}'
    class="contacts-form"
    method="post"
    action="<?= $escaper->escapeUrl($block->getUrl('contact/index/post')) ?>">

    <?= $block->getBlockHtml('formkey') ?>

    <h2 class="contacts-form-title">
        <?= $escaper->escapeHtml(__('Write us')) ?>
    </h2>

    <input name="username"
        id="username"
        type="text"
        placeholder="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
        class="contacts-form-input"
        data-validate='{"required":true, "max_text_length":15}' />

    <input name="phone"
        id="phone"
        type="text"
        placeholder="<?= $escaper->escapeHtmlAttr(__('Phone')) ?>"
        class="contacts-form-input"
        data-validate='{"required":true, "validate-phoneStrict":true}' />

    <input name="email"
        id="email"
        type="email"
        placeholder="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
        class="contacts-form-input"
        data-validate='{"required":true, "validate-email":true}' />

    <textarea name="message"
        placeholder="<?= $escaper->escapeHtmlAttr(__('Message')) ?>"
        class="contacts-form-input contacts-message"
        data-validate='{"required":true}'></textarea>

    <button type="submit" class="contacts-form-button">
        <?= $escaper->escapeHtml(__('Send')) ?>
    </button>

</form>

<script type="text/x-magento-init">
    {
    "#my-form": {
        "validation": {}
    }
}
</script>
