<form id="my-form"
    data-mage-init='{"validation":{}}'
    class="contacts-form"
    method="post"
    action="<?= $escaper->escapeUrl($block->getUrl('magstore/index/post')) ?>">

    <?= $block->getBlockHtml('formkey') ?>

    <h2 class="contacts-form-title">
        <?= $escaper->escapeHtml(__('Write us')) ?>
    </h2>

    <input name="name"
        id="name"
        type="text"
        placeholder="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
        class="contacts-form-input"
        data-validate='{"required":true, "max_text_length":15}' />

    <input name="telephone"
        id="telephone"
        type="text"
        placeholder="<?= $escaper->escapeHtmlAttr(__('Phone')) ?>"
        class="contacts-form-input"
        data-validate='{"required":true, "validate-phoneStrict":true}' />

    <input name="email"
        id="email"
        type="email"
        placeholder="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
        class="contacts-form-input"
        data-validate='{"required":true, "validate-email":true}' />

    <select name="comment"
        class="contacts-form-input"
        data-validate='{"required":true}'>
        <option value="Замовлення зворотнього дзвінка"><?= $escaper->escapeHtmlAttr(__('Замовлення зворотнього дзвінка')) ?></option>
        <option value="Консультація"><?= $escaper->escapeHtmlAttr(__('Консультація')) ?></option>
        <option value="Інше"><?= $escaper->escapeHtmlAttr(__('Інше')) ?></option>

    </select>

    <button type="submit" class="contacts-form-button">
        <?= $escaper->escapeHtml(__('Sent')) ?>
    </button>

</form>

<script type="text/x-magento-init">
    {
    "#my-form": {
        "validation": {}
    }
}
</script>
