<?php

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \MagStore\ProductFeatures\ViewModel\SliderProducts $viewModel */

$viewModel = $block->getData('view_model');
$products = $viewModel->getCarouselProducts();

if (empty($products)): return;
endif;
?>

<div class="carousel-container">
    <div id="carousel_test" class="carousel-test-list">
        <?php foreach ($products as $product): ?>
            <div class="item product-item">
                <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>" class="product-link">
                    <img class="carousel-img"
                        src="<?= $block->escapeUrl($viewModel->getImageUrl($product)) ?>"
                        alt="<?= $block->escapeHtmlAttr($product->getName()) ?>" />

                    <div class="carousel-description">
                        <strong class="product-name"><?= $block->escapeHtml($product->getName()) ?></strong>
                        <span class="price"><?= /* @noEscape */ $product->getFormatedPrice() ?></span>
                    </div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/x-magento-init">
    {
    "#carousel_test": {
        "carousel_test": {
            "slidesToShow": 2,
            "slidesToScroll": 1,
            "dots": true,
            "infinite": true,
            "autoplay": true,
            "arrows": false,
            "responsive": [
                { "breakpoint": 1024, "settings": { "slidesToShow": 2 } },
                { "breakpoint": 768, "settings": { "slidesToShow": 2 } }
            ]
        }
    }
}
</script>
