<div name="about-us-block">
    <h1><?= $escaper->escapeHtml(__('About us')) ?></h1>
    <p><?= $escaper->escapeHtml(__("We weren't looking to start a business. We were just looking for a jacket that actually worked. After wasting time and money on things that broke, faded, or just didn't feel right, we decided to make our own.")) ?></p>

    <p><?= $escaper->escapeHtml(__('At Store, we believe you shouldn&apos;t have to choose between quality and conscience. We spent months sourcing the best materials and vetting our partners to ensure that every item we ship is something we&apos;re proud of.')) ?></p>
</div>
