<div name="contacts-block">
    <h1><?= $escaper->escapeHtml(__('Contacts')) ?></h1>
    <ul>
        <li>
            <p><?= $escaper->escapeHtml(__('Email:')) ?></p>
            <p><?= $escaper->escapeHtml(__('hello@yourstore.com')) ?></p>
        </li>
        <li>
            <p><?= $escaper->escapeHtml(__('Socials:')) ?></p>
            <p><?= $escaper->escapeHtml(__('@YourStoreName (IG/TikTok)')) ?></p>
        </li>
    </ul>
</div>
