<?php

/** @var \Magento\Customer\Block\Widget\Name $block */
?>
<div class="field field-name-firstname required">
    <div class="control">
        <input type="text"
            id="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>"
            name="<?= $block->escapeHtmlAttr($block->getFieldName('firstname')) ?>"
            value="<?= $block->escapeHtmlAttr($block->getObject()->getFirstname()) ?>"
            class="input-text required-entry"
            data-validate='{"required":true, "cyrillicVal":true}'
            placeholder="<?= $block->escapeHtmlAttr(__("Ім'я")) ?>">
    </div>
</div>

<div class="field field-name-lastname required">
    <div class="control">
        <input type="text"
            id="<?= $block->escapeHtmlAttr($block->getFieldId('lastname')) ?>"
            name="<?= $block->escapeHtmlAttr($block->getFieldName('lastname')) ?>"
            value="<?= $block->escapeHtmlAttr($block->getObject()->getLastname()) ?>"
            class="input-text required-entry"
            data-validate='{"required":true, "cyrillicVal":true}'
            placeholder="<?= $block->escapeHtmlAttr(__("Прізвище")) ?>">
    </div>
</div>
