<?php

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div id="custom-tabs" class="product data items" name="custom-tabs"
    data-mage-init='{
        "tabs": {
            "openedState": "active",
            "collapsible": true,
            "active": 0,
            "animate": {"duration": 200}
        },
        "tabsSliderfix": {}
     }'>

    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-text">
            <?= $escaper->escapeHtml(__('Information')) ?>
        </a>
    </div>
    <div id="tab-popup" class="item content" data-role="content">
        <?= $block->getChildHtml('contact.content') ?>
    </div>

    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-slider">
            <?= $escaper->escapeHtml(__('Slider')) ?>
        </a>
    </div>
    <div id="tab-slider" class="item content" data-role="content" style="display:none;">
        <?= $block->getChildHtml('slider.content') ?>
    </div>
</div>

<script>
    require([
        'jquery',
        'mage/tabs'
    ], function($) {
        var tabs = $('#custom-tabs');

        tabs.on('beforeOpen', function(event) {
            if ($(event.target).attr('id') === 'tab-slider') {
                $(event.target).show();
            }
        });
        tabs.on('dimensionsChanged', function() {
            setTimeout(function() {
                $(window).trigger('resize');
                $('body').trigger('contentUpdated');
            }, 250);
        });
    });
</script>
